stages:
- name: Publish--vuejs image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: reg.406.csie.nuu.edu.tw
    env:
      PLUGIN_BUILD_ARGS: --progress=tty --network=host
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MTU: "1000"
- name: deploy apps
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:bitnami-node
      version: 12.0.1
      answers:
        getAppFromExternalRepository: "true"
        repository: https://github.com/smarthome-csie-nuu-edu-tw/vue-template-chart-no-image
        revision: main
        service.type: NodePort
      name: ${CICD_GIT_REPO_NAME}-node
      targetNamespace: ${CICD_GIT_REPO_NAME}
  - applyAppConfig:
      catalogTemplate: cattle-global-data:bitnami-node
      version: 12.0.1
      answers:
        ingress.enabled: "true"
        ingress.hostname: "vue-with-image.120.105.129.176.xip.io"
        ingress.tls: "true"
        getAppFromExternalRepository: "true"
        repository: https://github.com/smarthome-csie-nuu-edu-tw/vue-template-chart-no-image
        revision: main
        service.type: NodePort
      name: ${CICD_GIT_REPO_NAME}-xip
      targetNamespace: ${CICD_GIT_REPO_NAME}   
notification: {}
