#### 使用 Node 的版本(作為編譯)
FROM dockerhub/library/node:11-stretch AS builder
# Node 在容器內的位置
WORKDIR /home/node
# 編譯與安裝環境
COPY . / /home/node/
RUN ls && \
    npm install -D vuepress && \
    ls
# 修正預設處理資料夾路徑
WORKDIR /home/node/app
